/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'twer' at '3/18/15 6:08 PM' with Gradle 2.2.1
 *
 * @author twer, @date 3/18/15 6:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
